export type Category = {
  id: string;
  name: string;
  icon: string;
  words: string[];
};

export const CATEGORIES: Category[] = [
  {
    "id": "everyday_objects",
    "name": "Everyday Objects",
    "icon": "🏠",
    "words": [
      "Toothbrush",
      "Bicycle",
      "Umbrella",
      "Backpack",
      "Clock",
      "Lamp",
      "Chair",
      "Laptop",
      "Smartphone",
      "Wallet",
      "Keys",
      "Glasses",
      "Mirror",
      "Pillow",
      "Towel",
      "Sofa",
      "Refrigerator",
      "Microwave",
      "Oven",
      "Washing Machine",
      "Scissors",
      "Pen",
      "Notebook",
      "Coffee Mug",
      "Spoon",
      "Fork",
      "Knife",
      "Plate",
      "Bowl",
      "Pan",
      "Pot",
      "Toaster",
      "Blender",
      "Kettle",
      "Broom",
      "Mop",
      "Vacuum Cleaner",
      "Trash Can",
      "Iron",
      "Ironing Board",
      "Hanger",
      "Laundry Basket",
      "Hair Dryer",
      "Comb",
      "Brush",
      "Shampoo",
      "Soap",
      "Toothpaste",
      "Toilet Paper",
      "Plunger",
      "Bathtub",
      "Shower",
      "Sink",
      "Toilet",
      "Rug",
      "Carpet",
      "Curtain",
      "Window",
      "Door",
      "Table",
      "Desk",
      "Bookshelf",
      "Bed",
      "Mattress",
      "Blanket",
      "Sheet",
      "Fan",
      "Heater",
      "Air Conditioner",
      "Television",
      "Remote Control",
      "Speaker",
      "Headphones",
      "Charger",
      "Battery",
      "Flashlight",
      "Candle",
      "Matches",
      "Lighter",
      "Extension Cord",
      "Power Strip",
      "Light Bulb",
      "Screwdriver",
      "Hammer",
      "Wrench",
      "Pliers",
      "Nail",
      "Screw",
      "Tape Measure",
      "Drill",
      "Bucket",
      "Sponge",
      "Dish Soap",
      "Paper Towel",
      "Napkin",
      "Tissue",
      "Stapler",
      "Tape",
      "Glue",
      "Paperclip",
      "Tabo",
      "Walis Tambo",
      "Walis Tingting",
      "Kalan",
      "Kaldero",
      "Kawali",
      "Sandok",
      "Banig",
      "Kulambo",
      "Tsinelas",
      "Planggana",
      "Palayok",
      "Duyan",
      "Abaniko",
      "Sangkalan",
      "Kudkuran",
      "Bilao",
      "Batya",
      "Timba",
      "Siyanse",
      "Rubber Band",
      "Ruler",
      "Eraser",
      "Pencil",
      "Marker",
      "Highlighter",
      "Calculator",
      "Envelope",
      "Stamp",
      "Mailbox",
      "Newspaper",
      "Magazine",
      "Book",
      "Bookmark",
      "Calendar",
      "Picture Frame",
      "Vase",
      "Plant",
      "Watering Can",
      "Lawn Mower",
      "Rake",
      "Shovel",
      "Hose",
      "Wheelbarrow",
      "Gloves",
      "Hat",
      "Scarf",
      "Jacket",
      "Coat",
      "Shirt",
      "Pants",
      "Shorts",
      "Dress",
      "Skirt",
      "Socks",
      "Shoes",
      "Boots",
      "Sandals",
      "Slippers",
      "Belt",
      "Tie",
      "Watch",
      "Ring",
      "Necklace",
      "Bracelet",
      "Earrings",
      "Sunglasses",
      "Purse",
      "Bag",
      "Suitcase",
      "Coin",
      "Cash",
      "Credit Card",
      "Receipt",
      "Ticket",
      "Passport",
      "ID Card",
      "Driver's License",
      "Camera",
      "Tripod",
      "Microphone",
      "Projector",
      "Screen",
      "Keyboard",
      "Mouse",
      "Monitor",
      "Printer",
      "Scanner",
      "Router",
      "Modem",
      "USB Drive",
      "Hard Drive",
      "Webcam",
      "Tablet",
      "E-reader",
      "Smartwatch",
      "Fitness Tracker",
      "Thermostat",
      "Smoke Detector",
      "Alarm Clock",
      "Scale",
      "Tape Dispenser",
      "Hole Punch",
      "Whiteboard",
      "Corkboard",
      "Push Pin",
      "Thumbtack",
      "Clipboard",
      "Folder",
      "Binder",
      "Notepad",
      "Sticky Note",
      "Briefcase",
      "Duffel Bag",
      "Tote Bag",
      "Gym Bag",
      "Shoebox",
      "Jewelry Box",
      "Safe",
      "Lock",
      "Key",
      "Doorbell",
      "Doormat",
      "Mail Slot",
      "Porch Swing",
      "Hammock",
      "Grill",
      "Patio Table",
      "Lawn Chair",
      "Bird Feeder",
      "Birdhouse",
      "Wind Chime",
      "Garden Gnome",
      "Pool",
      "Trampoline",
      "Swing Set",
      "Kumot",
      "Unan",
      "Kamiseta",
      "Barong Tagalog",
      "Saya",
      "Salakot",
      "Panyo",
      "Pamaypay",
      "Arinola",
      "Plantsa",
      "Lamesa",
      "Upuan",
      "Aparador",
      "Estante",
      "Punda",
      "Kobrekama",
      "Basahan",
      "Sipilyo",
      "Suklay",
      "Bimpo",
      "Sabon",
      "Kandila",
      "Posporo",
      "Lapis",
      "Papel",
      "Gunting",
      "Karayom",
      "Sinulid",
      "Butones",
      "Sapatos",
      "Medyas",
      "Singsing",
      "Kwintas",
      "Hikaw",
      "Relos",
      "Salamin",
      "Pitaka",
      "Barya",
      "Sukli",
      "Resibo",
      "Bote",
      "Baso",
      "Tasa",
      "Plato",
      "Mangkok",
      "Kutsara",
      "Tinidor",
      "Kutsilyo",
      "Platito"
    ]
  },
  {
    "id": "famous_people",
    "name": "Famous People",
    "icon": "🦸‍♀️",
    "words": [
      "Albert Einstein",
      "Marilyn Monroe",
      "Michael Jackson",
      "Elon Musk",
      "Taylor Swift",
      "Barack Obama",
      "Leonardo DiCaprio",
      "Oprah Winfrey",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Beyoncé",
      "Steve Jobs",
      "Nelson Mandela",
      "Serena Williams",
      "Will Smith",
      "Tom Cruise",
      "Angelina Jolie",
      "Brad Pitt",
      "Johnny Depp",
      "Lady Gaga",
      "Justin Bieber",
      "Katy Perry",
      "Rihanna",
      "Drake",
      "Eminem",
      "Kanye West",
      "Kim Kardashian",
      "Kylie Jenner",
      "Selena Gomez",
      "Ariana Grande",
      "Dwayne Johnson",
      "Kevin Hart",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Stephen King",
      "J.K. Rowling",
      "George R.R. Martin",
      "William Shakespeare",
      "Charles Dickens",
      "Mark Twain",
      "Abraham Lincoln",
      "George Washington",
      "Winston Churchill",
      "Martin Luther King Jr.",
      "Mahatma Gandhi",
      "Mother Teresa",
      "Princess Diana",
      "Queen Elizabeth II",
      "Pope Francis",
      "Dalai Lama",
      "Bill Gates",
      "Mark Zuckerberg",
      "Jeff Bezos",
      "Warren Buffett",
      "Richard Branson",
      "Walt Disney",
      "Steven Spielberg",
      "Quentin Tarantino",
      "Martin Scorsese",
      "Christopher Nolan",
      "Tom Hanks",
      "Meryl Streep",
      "Denzel Washington",
      "Morgan Freeman",
      "Samuel L. Jackson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Stone",
      "Natalie Portman",
      "Anne Hathaway",
      "Manny Pacquiao",
      "Jose Rizal",
      "Lea Salonga",
      "Pia Wurtzbach",
      "Catriona Gray",
      "Vice Ganda",
      "Kathryn Bernardo",
      "Daniel Padilla",
      "Nadine Lustre",
      "James Reid",
      "Liza Soberano",
      "Enrique Gil",
      "Coco Martin",
      "Judy Ann Santos",
      "Piolo Pascual",
      "John Lloyd Cruz",
      "Bea Alonzo",
      "Sarah Geronimo",
      "Regine Velasquez",
      "Gary Valenciano",
      "Martin Nievera",
      "Sharon Cuneta",
      "Vilma Santos",
      "Nora Aunor",
      "Fernando Poe Jr.",
      "Dolphy",
      "Vic Sotto",
      "Joey de Leon",
      "Tito Sotto",
      "Maine Mendoza",
      "Alden Richards",
      "Anne Curtis",
      "Vhong Navarro",
      "Toni Gonzaga",
      "Alex Gonzaga",
      "Heart Evangelista",
      "Marian Rivera",
      "Dingdong Dantes",
      "Richard Gutierrez",
      "Angel Locsin",
      "Chris Hemsworth",
      "Chris Evans",
      "Robert Downey Jr.",
      "Chris Pratt",
      "Tom Holland",
      "Zendaya",
      "Timothée Chalamet",
      "Florence Pugh",
      "Margot Robbie",
      "Ryan Gosling",
      "Ryan Reynolds",
      "Hugh Jackman",
      "Keanu Reeves",
      "Jackie Chan",
      "Bruce Lee",
      "Muhammad Ali",
      "Mike Tyson",
      "LeBron James",
      "Michael Jordan",
      "Kobe Bryant",
      "Tiger Woods",
      "Roger Federer",
      "Rafael Nadal",
      "Novak Djokovic",
      "Usain Bolt",
      "Michael Phelps",
      "Simone Biles",
      "Tom Brady",
      "Peyton Manning",
      "David Beckham",
      "Elvis Presley",
      "The Beatles",
      "Freddie Mercury",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Aretha Franklin",
      "Stevie Wonder",
      "Ray Charles",
      "Frank Sinatra",
      "Bob Dylan",
      "Paul McCartney",
      "John Lennon",
      "Elton John",
      "Madonna",
      "Cher",
      "Adele",
      "Ed Sheeran",
      "Bruno Mars",
      "The Weeknd",
      "Billie Eilish",
      "Dua Lipa",
      "Harry Styles",
      "Shawn Mendes",
      "Post Malone",
      "Travis Scott",
      "Kendrick Lamar",
      "J. Cole",
      "Nicki Minaj",
      "Cardi B",
      "Megan Thee Stallion",
      "Doja Cat",
      "Olivia Rodrigo",
      "Bad Bunny",
      "Rosalía",
      "J Balvin",
      "Maluma",
      "Shakira",
      "Jennifer Lopez",
      "Ricky Martin",
      "Andres Bonifacio",
      "Emilio Aguinaldo",
      "Apolinario Mabini",
      "Juan Luna",
      "Melchora Aquino",
      "Gabriela Silang",
      "Lapu-Lapu",
      "Marcelo H. del Pilar",
      "Gregorio del Pilar",
      "Antonio Luna",
      "Rodrigo Duterte",
      "Ferdinand Marcos",
      "Corazon Aquino",
      "Fidel V. Ramos",
      "Gloria Macapagal Arroyo",
      "Benigno Aquino III",
      "Bongbong Marcos",
      "Leni Robredo",
      "Miriam Defensor Santiago",
      "Grace Poe",
      "Enrique Iglesias",
      "Marc Anthony",
      "Celine Dion",
      "Mariah Carey",
      "Shania Twain",
      "Garth Brooks",
      "Johnny Cash",
      "Dolly Parton",
      "Willie Nelson",
      "Blake Shelton",
      "Carrie Underwood",
      "Luke Bryan",
      "Miranda Lambert",
      "Keith Urban",
      "Tim McGraw",
      "Faith Hill",
      "Kelly Clarkson",
      "Simon Cowell",
      "Gordon Ramsay",
      "Jamie Oliver",
      "Carlos Yulo",
      "Hidilyn Diaz",
      "Efren Bata Reyes",
      "Margarita Fores",
      "Kenneth Cobonpue",
      "Michael Cinco",
      "Rajo Laurel",
      "Brillante Mendoza",
      "Lav Diaz",
      "Jaclyn Jose",
      "Neil Armstrong",
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Sally Ride",
      "Amelia Earhart",
      "Wright Brothers",
      "Thomas Edison",
      "Nikola Tesla",
      "Alexander Graham Bell",
      "Marie Curie",
      "Isaac Newton",
      "Galileo Galilei",
      "Charles Darwin",
      "Sigmund Freud",
      "Carl Jung",
      "Stephen Hawking",
      "Frida Kahlo",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Michelangelo",
      "Claude Monet",
      "Salvador Dalí",
      "Andy Warhol",
      "Jackson Pollock",
      "Georgia O'Keeffe"
    ]
  },
  {
    "id": "foods_drinks",
    "name": "Foods & Drinks",
    "icon": "🍕",
    "words": [
      "Pizza",
      "Sushi",
      "Hamburger",
      "Ice Cream",
      "Coffee",
      "Tea",
      "Taco",
      "Pasta",
      "Pancake",
      "Waffle",
      "Chocolate",
      "Steak",
      "Salad",
      "Sandwich",
      "Soup",
      "Donut",
      "Croissant",
      "Fried Chicken",
      "Smoothie",
      "Lemonade",
      "Apple",
      "Banana",
      "Orange",
      "Grapes",
      "Strawberry",
      "Blueberry",
      "Watermelon",
      "Mango",
      "Pineapple",
      "Kiwi",
      "Peach",
      "Plum",
      "Cherry",
      "Pear",
      "Avocado",
      "Tomato",
      "Potato",
      "Carrot",
      "Broccoli",
      "Spinach",
      "Adobo",
      "Sinigang",
      "Lechon",
      "Halo-Halo",
      "Sisig",
      "Kare-Kare",
      "Pancit",
      "Lumpia",
      "Balut",
      "Taho",
      "Isaw",
      "Dinuguan",
      "Buko Pie",
      "Puto",
      "Kutsinta",
      "Bibingka",
      "Palitaw",
      "Tapsilog",
      "Longganisa",
      "Tocino",
      "Crispy Pata",
      "Bulalo",
      "Tinola",
      "Pinakbet",
      "Laing",
      "Bicol Express",
      "Chicharon",
      "Ensaymada",
      "Pan de Sal",
      "Champorado",
      "Turon",
      "Banana Cue",
      "Kamote Cue",
      "Kwek-Kwek",
      "Fishball",
      "Kikiam",
      "Proben",
      "Tupig",
      "Suman",
      "Leche Flan",
      "Lettuce",
      "Onion",
      "Garlic",
      "Mushroom",
      "Corn",
      "Peas",
      "Beans",
      "Rice",
      "Bread",
      "Cheese",
      "Milk",
      "Butter",
      "Yogurt",
      "Egg",
      "Bacon",
      "Sausage",
      "Ham",
      "Turkey",
      "Chicken",
      "Beef",
      "Pork",
      "Fish",
      "Salmon",
      "Tuna",
      "Shrimp",
      "Crab",
      "Lobster",
      "Oyster",
      "Clam",
      "Mussel",
      "Cake",
      "Pie",
      "Cookie",
      "Brownie",
      "Muffin",
      "Cupcake",
      "Candy",
      "Gum",
      "Chips",
      "Popcorn",
      "Pretzel",
      "Cracker",
      "Cereal",
      "Oatmeal",
      "Pudding",
      "Jello",
      "Honey",
      "Jam",
      "Jelly",
      "Peanut Butter",
      "Mustard",
      "Ketchup",
      "Mayonnaise",
      "Hot Sauce",
      "Soy Sauce",
      "Vinegar",
      "Olive Oil",
      "Salt",
      "Pepper",
      "Sugar",
      "Flour",
      "Water",
      "Juice",
      "Soda",
      "Cola",
      "Beer",
      "Wine",
      "Vodka",
      "Rum",
      "Whiskey",
      "Tequila",
      "Gin",
      "Cocktail",
      "Milkshake",
      "Hot Chocolate",
      "Iced Tea",
      "Espresso",
      "Cappuccino",
      "Latte",
      "Mocha",
      "Burrito",
      "Enchilada",
      "Quesadilla",
      "Nachos",
      "Fajita",
      "Guacamole",
      "Salsa",
      "Hummus",
      "Falafel",
      "Shawarma",
      "Kebab",
      "Curry",
      "Naan",
      "Samosa",
      "Pad Thai",
      "Pho",
      "Ramen",
      "Dumpling",
      "Spring Roll",
      "Bao",
      "Dim Sum",
      "Fried Rice",
      "Noodle",
      "Macaroni",
      "Spaghetti",
      "Lasagna",
      "Ravioli",
      "Gnocchi",
      "Pesto",
      "Marinara",
      "Alfredo",
      "Meatball",
      "Burger",
      "Hot Dog",
      "French Fries",
      "Onion Ring",
      "Chicken Nugget",
      "Tater Tot",
      "Hash Brown",
      "Coleslaw",
      "Calamansi Juice",
      "Sago't Gulaman",
      "Buko Pandan",
      "Ube Halaya",
      "Cassava Cake",
      "Sapin-Sapin",
      "Biko",
      "Ginataang Bilo-Bilo",
      "Arroz Caldo",
      "Goto",
      "Pancit Palabok",
      "Pancit Canton",
      "Pancit Malabon",
      "Pancit Bihon",
      "Dinakdakan",
      "Igado",
      "Papaitan",
      "Kinilaw",
      "Inasal",
      "Chicken Joy",
      "Baked Bean",
      "Mac and Cheese",
      "Cornbread",
      "Biscuit",
      "Gravy",
      "Mashed Potato",
      "Sweet Potato",
      "Squash",
      "Zucchini",
      "Eggplant",
      "Bell Pepper",
      "Jalapeno",
      "Chili",
      "Asparagus",
      "Brussels Sprout",
      "Cauliflower",
      "Celery",
      "Cucumber",
      "Radish",
      "Turnip",
      "Beet",
      "Cabbage",
      "Kale",
      "Artichoke",
      "Leek",
      "Scallion",
      "Shallot",
      "Ginger",
      "Turmeric",
      "Cinnamon",
      "Nutmeg",
      "Clove",
      "Vanilla",
      "Mint",
      "Basil",
      "Oregano",
      "Thyme",
      "Rosemary",
      "Parsley",
      "Cilantro"
    ]
  },
  {
    "id": "animals",
    "name": "Animals",
    "icon": "🦁",
    "words": [
      "Lion",
      "Tiger",
      "Elephant",
      "Giraffe",
      "Penguin",
      "Dolphin",
      "Whale",
      "Kangaroo",
      "Koala",
      "Panda",
      "Gorilla",
      "Zebra",
      "Cheetah",
      "Wolf",
      "Bear",
      "Eagle",
      "Owl",
      "Snake",
      "Crocodile",
      "Frog",
      "Butterfly",
      "Dog",
      "Cat",
      "Horse",
      "Cow",
      "Pig",
      "Sheep",
      "Goat",
      "Chicken",
      "Duck",
      "Carabao",
      "Tarsier",
      "Tamaraw",
      "Philippine Eagle",
      "Butanding",
      "Maya",
      "Askal",
      "Pusakal",
      "Bangus",
      "Tilapia",
      "Pawikan",
      "Dugong",
      "Pilandok",
      "Kalaw",
      "Tuko",
      "Ahas",
      "Buwaya",
      "Baboy Ramo",
      "Langgam",
      "Ipis",
      "Lamok",
      "Langaw",
      "Gagamba",
      "Alupihan",
      "Tutubi",
      "Paruparo",
      "Pukyutan",
      "Alitaptap",
      "Bulate",
      "Suso",
      "Turkey",
      "Goose",
      "Rabbit",
      "Mouse",
      "Rat",
      "Hamster",
      "Guinea Pig",
      "Ferret",
      "Hedgehog",
      "Squirrel",
      "Chipmunk",
      "Raccoon",
      "Skunk",
      "Opossum",
      "Beaver",
      "Otter",
      "Badger",
      "Fox",
      "Coyote",
      "Jackal",
      "Hyena",
      "Leopard",
      "Jaguar",
      "Panther",
      "Cougar",
      "Lynx",
      "Bobcat",
      "Moose",
      "Elk",
      "Deer",
      "Antelope",
      "Gazelle",
      "Bison",
      "Buffalo",
      "Camel",
      "Llama",
      "Alpaca",
      "Rhino",
      "Hippo",
      "Walrus",
      "Seal",
      "Sea Lion",
      "Manatee",
      "Shark",
      "Stingray",
      "Octopus",
      "Squid",
      "Jellyfish",
      "Starfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Seahorse",
      "Turtle",
      "Tortoise",
      "Lizard",
      "Iguana",
      "Chameleon",
      "Gecko",
      "Alligator",
      "Toad",
      "Salamander",
      "Newt",
      "Ostrich",
      "Emu",
      "Flamingo",
      "Pelican",
      "Swan",
      "Peacock",
      "Parrot",
      "Macaw",
      "Cockatoo",
      "Canary",
      "Finch",
      "Pigeon",
      "Dove",
      "Crow",
      "Raven",
      "Hawk",
      "Falcon",
      "Vulture",
      "Woodpecker",
      "Hummingbird",
      "Robin",
      "Sparrow",
      "Blue Jay",
      "Cardinal",
      "Bee",
      "Wasp",
      "Hornet",
      "Ant",
      "Termite",
      "Beetle",
      "Ladybug",
      "Firefly",
      "Grasshopper",
      "Cricket",
      "Mantis",
      "Roach",
      "Fly",
      "Mosquito",
      "Moth",
      "Spider",
      "Scorpion",
      "Tick",
      "Flea",
      "Centipede",
      "Millipede",
      "Worm",
      "Snail",
      "Slug",
      "Clam",
      "Oyster",
      "Mussel",
      "Cuttlefish",
      "Nautilus",
      "Barnacle",
      "Anemone",
      "Maya Bird",
      "Agila",
      "Manok",
      "Bibe",
      "Pabo",
      "Gansa",
      "Pugo",
      "Kalapati",
      "Uwak",
      "Kuwago",
      "Baboy",
      "Baka",
      "Kalabaw",
      "Kabayo",
      "Kambing",
      "Tupa",
      "Aso",
      "Pusa",
      "Daga",
      "Paniki",
      "Coral",
      "Sponge",
      "Urchin",
      "Sand Dollar",
      "Sea Cucumber",
      "Platypus",
      "Echidna",
      "Wombat",
      "Tasmanian Devil",
      "Quokka",
      "Sloth",
      "Armadillo",
      "Anteater",
      "Pangolin",
      "Aardvark",
      "Meerkat",
      "Mongoose",
      "Lemur",
      "Baboon",
      "Chimpanzee",
      "Orangutan",
      "Macaque",
      "Gibbon",
      "Tapir",
      "Capybara",
      "Porcupine",
      "Chinchilla",
      "Gerbil",
      "Vole",
      "Shrew",
      "Mole",
      "Bat",
      "Flying Fox",
      "Vampire Bat",
      "Fruit Bat",
      "Piranha",
      "Goldfish",
      "Koi",
      "Guppy",
      "Betta"
    ]
  },
  {
    "id": "brands_logos",
    "name": "Brands & Logos",
    "icon": "🏢",
    "words": [
      "Apple",
      "Nike",
      "Coca-Cola",
      "Google",
      "Amazon",
      "Microsoft",
      "McDonald's",
      "Starbucks",
      "Disney",
      "Netflix",
      "Facebook",
      "Twitter",
      "Instagram",
      "Tesla",
      "Toyota",
      "Samsung",
      "Adidas",
      "Pepsi",
      "Sony",
      "Lego",
      "Jollibee",
      "San Miguel",
      "Bench",
      "Penshoppe",
      "SM",
      "BDO",
      "Globe",
      "Smart",
      "PLDT",
      "Mang Inasal",
      "Chowking",
      "Red Ribbon",
      "Goldilocks",
      "Datu Puti",
      "Silver Swan",
      "Puregold",
      "Ayala",
      "Cebu Pacific",
      "Philippine Airlines",
      "Meralco",
      "GMA",
      "ABS-CBN",
      "TV5",
      "Shopee",
      "Lazada",
      "Grab",
      "Foodpanda",
      "Angkas",
      "JoyRide",
      "GCash",
      "Ford",
      "Honda",
      "Chevrolet",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Volkswagen",
      "Porsche",
      "Ferrari",
      "Lamborghini",
      "Rolex",
      "Gucci",
      "Louis Vuitton",
      "Chanel",
      "Prada",
      "Hermes",
      "Cartier",
      "Tiffany & Co.",
      "Burberry",
      "Dior",
      "Zara",
      "H&M",
      "Forever 21",
      "Gap",
      "Old Navy",
      "Levi's",
      "Wrangler",
      "Calvin Klein",
      "Tommy Hilfiger",
      "Ralph Lauren",
      "Target",
      "Walmart",
      "Costco",
      "IKEA",
      "Home Depot",
      "Lowe's",
      "Best Buy",
      "Macy's",
      "Nordstrom",
      "Kohl's",
      "Subway",
      "Burger King",
      "Wendy's",
      "Taco Bell",
      "KFC",
      "Domino's",
      "Pizza Hut",
      "Papa John's",
      "Chipotle",
      "Panera Bread",
      "Dunkin'",
      "Krispy Kreme",
      "Baskin-Robbins",
      "Dairy Queen",
      "Red Bull",
      "Monster",
      "Gatorade",
      "Powerade",
      "Sprite",
      "Dr Pepper",
      "Mountain Dew",
      "Fanta",
      "7-Up",
      "Lipton",
      "Snapple",
      "Hershey's",
      "Mars",
      "Nestle",
      "Cadbury",
      "Lindt",
      "Ferrero",
      "M&M's",
      "Snickers",
      "Twix",
      "KitKat",
      "Oreo",
      "Chips Ahoy",
      "Doritos",
      "Lay's",
      "Cheetos",
      "Pringles",
      "Ruffles",
      "Fritos",
      "Kellogg's",
      "General Mills",
      "Post",
      "Quaker",
      "Pillsbury",
      "Betty Crocker",
      "Duncan Hines",
      "Kraft",
      "Heinz",
      "Campbell's",
      "L'Oreal",
      "Maybelline",
      "CoverGirl",
      "MAC",
      "Sephora",
      "Ulta",
      "Bath & Body Works",
      "PayMaya",
      "BPI",
      "Metrobank",
      "Landbank",
      "UnionBank",
      "RCBC",
      "Security Bank",
      "Oishi",
      "Jack 'n Jill",
      "Mondelez",
      "Rebisco",
      "Universal Robina",
      "Century Tuna",
      "Mega Sardines",
      "555 Sardines",
      "San Marino",
      "Argentina Corned Beef",
      "Purefoods",
      "Tender Juicy",
      "CDO",
      "Victoria's Secret",
      "Gillette",
      "Colgate",
      "Crest",
      "Dove",
      "Pantene",
      "Head & Shoulders",
      "Old Spice",
      "Secret",
      "Axe",
      "Pampers",
      "Huggies",
      "Kleenex",
      "Bounty",
      "Charmin",
      "Tide",
      "Gain",
      "Downy",
      "Clorox",
      "Lysol",
      "Windex",
      "Dawn",
      "Cascade",
      "Duracell",
      "Energizer",
      "Bose",
      "JBL",
      "Beats",
      "Sennheiser",
      "Skullcandy",
      "Nintendo",
      "PlayStation",
      "Xbox",
      "Sega",
      "Atari",
      "EA",
      "Ubisoft",
      "Activision",
      "Blizzard",
      "Epic Games",
      "Marvel",
      "DC",
      "Warner Bros",
      "Universal",
      "Paramount",
      "Fox",
      "HBO",
      "Showtime",
      "Hulu",
      "Disney+",
      "Spotify",
      "Apple Music",
      "Pandora",
      "SoundCloud",
      "TikTok",
      "Snapchat",
      "Pinterest",
      "LinkedIn",
      "Reddit",
      "Tumblr",
      "Visa",
      "Mastercard",
      "American Express",
      "Discover",
      "PayPal",
      "Stripe",
      "Square",
      "Venmo",
      "Cash App",
      "Zelle",
      "Boeing",
      "Airbus",
      "SpaceX",
      "NASA",
      "Intel",
      "AMD",
      "Nvidia",
      "Qualcomm",
      "IBM",
      "Oracle"
    ]
  },
  {
    "id": "colors_shapes",
    "name": "Colors & Shapes",
    "icon": "🎨",
    "words": [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Orange",
      "Purple",
      "Pink",
      "Brown",
      "Black",
      "White",
      "Gray",
      "Silver",
      "Gold",
      "Bronze",
      "Copper",
      "Cyan",
      "Magenta",
      "Teal",
      "Navy",
      "Maroon",
      "Pula",
      "Bughaw",
      "Dilaw",
      "Luntian",
      "Itim",
      "Puti",
      "Bilog",
      "Parisukat",
      "Tatsulok",
      "Parihaba",
      "Abo",
      "Kayumanggi",
      "Rosas",
      "Kahel",
      "Lila",
      "Berdeng-Dilaw",
      "Bughaw-Luntian",
      "Tanso",
      "Pilak",
      "Ginto",
      "Oblong",
      "Habilog",
      "Hugis-Puso",
      "Hugis-Tala",
      "Hugis-Diyamante",
      "Kalahating Bilog",
      "Bilot",
      "Kudrado",
      "Alon",
      "Pataas",
      "Olive",
      "Lime",
      "Aqua",
      "Turquoise",
      "Indigo",
      "Violet",
      "Peach",
      "Coral",
      "Salmon",
      "Crimson",
      "Scarlet",
      "Ruby",
      "Burgundy",
      "Lavender",
      "Lilac",
      "Plum",
      "Orchid",
      "Fuchsia",
      "Rose",
      "Mint",
      "Forest Green",
      "Emerald",
      "Jade",
      "Khaki",
      "Beige",
      "Tan",
      "Ivory",
      "Cream",
      "Mustard",
      "Amber",
      "Rust",
      "Auburn",
      "Chocolate",
      "Coffee",
      "Caramel",
      "Charcoal",
      "Slate",
      "Ash",
      "Ebony",
      "Onyx",
      "Pearl",
      "Opal",
      "Sapphire",
      "Amethyst",
      "Topaz",
      "Circle",
      "Square",
      "Triangle",
      "Rectangle",
      "Oval",
      "Star",
      "Heart",
      "Diamond",
      "Cross",
      "Crescent",
      "Arrow",
      "Line",
      "Dot",
      "Sphere",
      "Cube",
      "Cylinder",
      "Cone",
      "Pyramid",
      "Prism",
      "Hexagon",
      "Octagon",
      "Pentagon",
      "Decagon",
      "Heptagon",
      "Nonagon",
      "Rhombus",
      "Parallelogram",
      "Trapezoid",
      "Kite",
      "Ellipse",
      "Spiral",
      "Zigzag",
      "Wave",
      "Curve",
      "Loop",
      "Polygon",
      "Polyhedron",
      "Tetrahedron",
      "Octahedron",
      "Dodecahedron",
      "Icosahedron",
      "Torus",
      "Tube",
      "Ring",
      "Disk",
      "Sector",
      "Segment",
      "Quadrant",
      "Hemisphere",
      "Arc",
      "Chord",
      "Tangent",
      "Secant",
      "Radius",
      "Diameter",
      "Perimeter",
      "Circumference",
      "Area",
      "Volume",
      "Surface",
      "Edge",
      "Vertex",
      "Face",
      "Angle",
      "Degree",
      "Acute",
      "Obtuse",
      "Right",
      "Straight",
      "Reflex",
      "Parallel",
      "Perpendicular",
      "Intersecting",
      "Symmetric",
      "Asymmetric",
      "Concave",
      "Convex",
      "Solid",
      "Hollow",
      "Flat",
      "Curved",
      "Crooked",
      "Bent",
      "Twisted",
      "Folded",
      "Wrinkled",
      "Smooth",
      "Rough",
      "Texture",
      "Pattern",
      "Grid",
      "Checkered",
      "Striped",
      "Spotted",
      "Polka Dot",
      "Plaid",
      "Tartan",
      "Chevron",
      "Herringbone",
      "Houndstooth",
      "Camouflage",
      "Tie-Dye",
      "Gradient",
      "Ombre",
      "Monochrome",
      "Polychrome",
      "Primary",
      "Secondary",
      "Tertiary",
      "Warm",
      "Cool",
      "Neutral",
      "Pastel",
      "Neon",
      "Fluorescent",
      "Metallic",
      "Matte",
      "Glossy",
      "Shiny",
      "Dull",
      "Bright",
      "Dark",
      "Light",
      "Pale",
      "Deep",
      "Vivid",
      "Muted",
      "Saturated",
      "Desaturated",
      "Opaque",
      "Transparent",
      "Translucent",
      "Clear",
      "Cloudy"
    ]
  },
  {
    "id": "countries_cities",
    "name": "Countries & Cities",
    "icon": "🌎",
    "words": [
      "Paris",
      "Tokyo",
      "New York",
      "London",
      "Rome",
      "Australia",
      "Brazil",
      "Canada",
      "Egypt",
      "France",
      "Germany",
      "India",
      "Italy",
      "Japan",
      "Mexico",
      "Spain",
      "United Kingdom",
      "United States",
      "China",
      "Russia",
      "Manila",
      "Cebu",
      "Davao",
      "Quezon City",
      "Makati",
      "Palawan",
      "Boracay",
      "Baguio",
      "Vigan",
      "Iloilo",
      "Bacolod",
      "Zamboanga",
      "Tagaytay",
      "Bohol",
      "Siargao",
      "Batanes",
      "Sagada",
      "Coron",
      "El Nido",
      "Puerto Princesa",
      "Pampanga",
      "Bulacan",
      "Laguna",
      "Batangas",
      "Cavite",
      "Rizal",
      "Tarlac",
      "Nueva Ecija",
      "Pangasinan",
      "La Union",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Seattle",
      "Denver",
      "Washington D.C.",
      "Boston",
      "Miami",
      "Atlanta",
      "San Francisco",
      "Las Vegas",
      "Orlando",
      "New Orleans",
      "Toronto",
      "Vancouver",
      "Montreal",
      "Calgary",
      "Ottawa",
      "Edmonton",
      "Quebec City",
      "Winnipeg",
      "Halifax",
      "Victoria",
      "Berlin",
      "Munich",
      "Frankfurt",
      "Hamburg",
      "Cologne",
      "Stuttgart",
      "Dusseldorf",
      "Leipzig",
      "Dresden",
      "Nuremberg",
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Malaga",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Bilbao",
      "Milan",
      "Naples",
      "Turin",
      "Palermo",
      "Genoa",
      "Bologna",
      "Florence",
      "Bari",
      "Catania",
      "Venice",
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Chongqing",
      "Tianjin",
      "Wuhan",
      "Dongguan",
      "Hong Kong",
      "Osaka",
      "Yokohama",
      "Nagoya",
      "Sapporo",
      "Fukuoka",
      "Kobe",
      "Kyoto",
      "Kawasaki",
      "Saitama",
      "Hiroshima",
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Ahmedabad",
      "Chennai",
      "Kolkata",
      "Surat",
      "Pune",
      "Jaipur",
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Wollongong",
      "Hobart",
      "Sao Paulo",
      "Rio de Janeiro",
      "Brasilia",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Porto Alegre",
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
      "Toluca",
      "Leon",
      "Juarez",
      "Torreon",
      "Querétaro",
      "Ilocos Norte",
      "Ilocos Sur",
      "Cagayan",
      "Isabela",
      "Bataan",
      "Zambales",
      "Aurora",
      "Quezon",
      "Mindoro",
      "Marinduque",
      "Romblon",
      "Albay",
      "Sorsogon",
      "Camarines Sur",
      "Camarines Norte",
      "Masbate",
      "Aklan",
      "Antique",
      "Capiz",
      "Guimaras",
      "Cairo",
      "Alexandria",
      "Giza",
      "Shubra El-Kheima",
      "Port Said",
      "Suez",
      "Luxor",
      "Aswan",
      "Asyut",
      "Ismailia",
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Kazan",
      "Nizhny Novgorod",
      "Chelyabinsk",
      "Samara",
      "Omsk",
      "Rostov-on-Don",
      "Argentina",
      "Chile",
      "Colombia",
      "Peru",
      "Venezuela",
      "Ecuador",
      "Bolivia",
      "Paraguay",
      "Uruguay",
      "Guyana",
      "South Africa",
      "Nigeria",
      "Kenya",
      "Ethiopia",
      "Ghana",
      "Tanzania",
      "Uganda",
      "Morocco",
      "Algeria",
      "Sudan",
      "Saudi Arabia",
      "Iran",
      "Turkey",
      "Iraq",
      "Israel",
      "UAE",
      "Jordan",
      "Lebanon",
      "Syria",
      "Yemen",
      "Thailand",
      "Vietnam",
      "Indonesia",
      "Malaysia",
      "Philippines",
      "Singapore",
      "South Korea",
      "North Korea",
      "Taiwan",
      "New Zealand",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Iceland",
      "Netherlands",
      "Belgium",
      "Switzerland",
      "Austria",
      "Greece"
    ]
  },
  {
    "id": "emotions_feelings",
    "name": "Emotions & Feelings",
    "icon": "😊",
    "words": [
      "Happy",
      "Sad",
      "Angry",
      "Excited",
      "Scared",
      "Nervous",
      "Surprised",
      "Bored",
      "Tired",
      "Confused",
      "Frustrated",
      "Proud",
      "Jealous",
      "Guilty",
      "Ashamed",
      "Embarrassed",
      "Disgusted",
      "Hopeful",
      "Lonely",
      "Loved",
      "Masaya",
      "Malungkot",
      "Galit",
      "Takot",
      "Kilig",
      "Inis",
      "Tampo",
      "Gulat",
      "Hiya",
      "Inip",
      "Tuwa",
      "Lungkot",
      "Poot",
      "Sindak",
      "Kaba",
      "Sabik",
      "Pagod",
      "Lito",
      "Sisi",
      "Sawi",
      "Inggit",
      "Panghihinayang",
      "Pag-asa",
      "Pangamba",
      "Gigil",
      "Pangulila",
      "Saya",
      "Hinagpis",
      "Ligaya",
      "Lungkot",
      "Joyful",
      "Miserable",
      "Furious",
      "Thrilled",
      "Terrified",
      "Anxious",
      "Amazed",
      "Apathetic",
      "Exhausted",
      "Perplexed",
      "Irritated",
      "Accomplished",
      "Envious",
      "Remorseful",
      "Humiliated",
      "Mortified",
      "Repulsed",
      "Optimistic",
      "Isolated",
      "Adored",
      "Ecstatic",
      "Depressed",
      "Enraged",
      "Elated",
      "Horrified",
      "Worried",
      "Astonished",
      "Uninterested",
      "Fatigued",
      "Baffled",
      "Annoyed",
      "Satisfied",
      "Covetous",
      "Regretful",
      "Disgraced",
      "Awkward",
      "Sickened",
      "Confident",
      "Abandoned",
      "Cherished",
      "Cheerful",
      "Heartbroken",
      "Livid",
      "Overjoyed",
      "Petrified",
      "Panicked",
      "Shocked",
      "Indifferent",
      "Drained",
      "Puzzled",
      "Agitated",
      "Triumphant",
      "Resentful",
      "Sorry",
      "Shameful",
      "Self-conscious",
      "Nauseated",
      "Positive",
      "Desolate",
      "Treasured",
      "Delighted",
      "Grieving",
      "Outraged",
      "Jubilant",
      "Alarmed",
      "Apprehensive",
      "Stunned",
      "Uncaring",
      "Weary",
      "Bewildered",
      "Exasperated",
      "Vindicated",
      "Spiteful",
      "Apologetic",
      "Guilt-ridden",
      "Flustered",
      "Revolted",
      "Expectant",
      "Forsaken",
      "Valued",
      "Glad",
      "Sorrowful",
      "Fuming",
      "Euphoric",
      "Frightened",
      "Uneasy",
      "Dumbfounded",
      "Detached",
      "Sleepy",
      "Flummoxed",
      "Vexed",
      "Smug",
      "Bitter",
      "Penitent",
      "Dishonored",
      "Bashful",
      "Appalled",
      "Sanguine",
      "Alienated",
      "Prized",
      "Pagkamangha",
      "Pagkadismaya",
      "Pagkamuhi",
      "Pagkainip",
      "Pagkabalisa",
      "Pagkahiya",
      "Pagmamalaki",
      "Pagsisisi",
      "Pagkagalak",
      "Pagdurusa",
      "Content",
      "Melancholy",
      "Incensed",
      "Gleeful",
      "Spooked",
      "Restless",
      "Startled",
      "Listless",
      "Sluggish",
      "Mystified",
      "Cross",
      "Arrogant",
      "Begrudging",
      "Contrite",
      "Degraded",
      "Shy",
      "Offended",
      "Assured",
      "Outcast",
      "Revered",
      "Merry",
      "Despondent",
      "Irate",
      "Radiant",
      "Intimidated",
      "Tense",
      "Awestruck",
      "Lethargic",
      "Burned-out",
      "Confounded",
      "Peeved",
      "Conceited",
      "Vindictive",
      "Repentant",
      "Timid",
      "Secure",
      "Estranged",
      "Worshipped",
      "Sunny",
      "Dejected",
      "Wrathful",
      "Buoyant",
      "Dreading",
      "Jittery",
      "Fascinated",
      "Passive",
      "Languid",
      "Disoriented",
      "Miffed",
      "Haughty",
      "Malicious",
      "Rueful",
      "Abased",
      "Sheepish",
      "Certain",
      "Solitary",
      "Idolized",
      "Peaceful",
      "Calm",
      "Relaxed",
      "Serene",
      "Tranquil",
      "Placid",
      "Composed",
      "Collected",
      "Mellow",
      "Soothed",
      "Amused",
      "Entertained",
      "Diverted",
      "Tickled",
      "Charmed",
      "Captivated",
      "Enthralled",
      "Engrossed",
      "Absorbed"
    ]
  },
  {
    "id": "hobbies_activities",
    "name": "Hobbies & Activities",
    "icon": "🎨",
    "words": [
      "Reading",
      "Writing",
      "Drawing",
      "Painting",
      "Photography",
      "Cooking",
      "Baking",
      "Gardening",
      "Fishing",
      "Hiking",
      "Camping",
      "Swimming",
      "Running",
      "Cycling",
      "Yoga",
      "Meditation",
      "Dancing",
      "Singing",
      "Playing Guitar",
      "Playing Piano",
      "Karaoke",
      "Basketball",
      "Sungka",
      "Patintero",
      "Tumbang Preso",
      "Luksong Baka",
      "Piko",
      "Sipa",
      "Tsismis",
      "Street Food Hopping",
      "Pagsasayaw",
      "Pagkanta",
      "Pagluluto",
      "Pagbabasa",
      "Pagsusulat",
      "Pagguhit",
      "Paglangoy",
      "Pagtatakbo",
      "Pagbibisikleta",
      "Pamimingwit",
      "Pag-akyat ng Bundok",
      "Pagtatanim",
      "Paglalaro ng Taguan",
      "Agawan Base",
      "Langit Lupa",
      "Ten-Twenty",
      "Chinese Garter",
      "Teks",
      "Holen",
      "Saranggola",
      "Knitting",
      "Crocheting",
      "Sewing",
      "Woodworking",
      "Pottery",
      "Sculpting",
      "Calligraphy",
      "Origami",
      "Scrapbooking",
      "Jewelry Making",
      "Gaming",
      "Board Games",
      "Chess",
      "Puzzles",
      "Crosswords",
      "Sudoku",
      "Magic Tricks",
      "Juggling",
      "Bowling",
      "Billiards",
      "Golf",
      "Tennis",
      "Soccer",
      "Baseball",
      "Volleyball",
      "Rugby",
      "Cricket",
      "Table Tennis",
      "Badminton",
      "Skiing",
      "Snowboarding",
      "Ice Skating",
      "Roller Skating",
      "Skateboarding",
      "Surfing",
      "Sailing",
      "Kayaking",
      "Canoeing",
      "Rowing",
      "Scuba Diving",
      "Snorkeling",
      "Rock Climbing",
      "Bouldering",
      "Martial Arts",
      "Karate",
      "Taekwondo",
      "Judo",
      "Boxing",
      "Wrestling",
      "Fencing",
      "Archery",
      "Horseback Riding",
      "Gymnastics",
      "Cheerleading",
      "Weightlifting",
      "Bodybuilding",
      "CrossFit",
      "Pilates",
      "Aerobics",
      "Zumba",
      "Ballet",
      "Tap Dancing",
      "Jazz Dancing",
      "Hip Hop Dancing",
      "Salsa Dancing",
      "Ballroom Dancing",
      "Acting",
      "Theater",
      "Improv",
      "Stand-up Comedy",
      "Filmmaking",
      "Animation",
      "Graphic Design",
      "Web Design",
      "Programming",
      "Coding",
      "Blogging",
      "Vlogging",
      "Podcasting",
      "Bird Watching",
      "Stargazing",
      "Astronomy",
      "Meteorology",
      "Geocaching",
      "Metal Detecting",
      "Foraging",
      "Mushroom Hunting",
      "Beekeeping",
      "Brewing",
      "Winemaking",
      "Coffee Roasting",
      "Tea Tasting",
      "Wine Tasting",
      "Mixology",
      "Baking Bread",
      "Cake Decorating",
      "Grilling",
      "Smoking Meat",
      "Fermenting",
      "Canning",
      "Preserving",
      "Candle Making",
      "Soap Making",
      "Perfume Making",
      "Leatherworking",
      "Blacksmithing",
      "Glassblowing",
      "Stained Glass",
      "Mosaic",
      "Macrame",
      "Weaving",
      "Spinning",
      "Felting",
      "Embroidery",
      "Cross-stitch",
      "Needlepoint",
      "Quilting",
      "Upholstery",
      "Restoration",
      "Upcycling",
      "Thrifting",
      "Antiquing",
      "Collecting",
      "Stamp Collecting",
      "Coin Collecting",
      "Card Collecting",
      "Comic Book Collecting",
      "Record Collecting",
      "Action Figure Collecting",
      "Model Building",
      "Gunpla",
      "Lego Building",
      "Diorama Making",
      "Miniature Painting",
      "Train Spotting",
      "Plane Spotting",
      "Car Spotting",
      "Bus Spotting",
      "Ship Spotting",
      "Travel",
      "Backpacking",
      "Road Tripping",
      "RVing",
      "Cruising",
      "Sightseeing",
      "Museum Going",
      "Gallery Hopping",
      "Concert Going",
      "Festival Going",
      "Volunteering",
      "Mentoring",
      "Tutoring",
      "Coaching",
      "Fostering Animals",
      "Community Gardening",
      "Activism",
      "Protesting",
      "Debating",
      "Public Speaking",
      "Learning Languages",
      "Studying History",
      "Researching",
      "Genealogy",
      "Philosophy",
      "Psychology",
      "Sociology",
      "Economics",
      "Politics",
      "Investing",
      "Trading",
      "Cryptocurrency",
      "Real Estate",
      "DIY Projects",
      "Home Improvement",
      "Interior Design",
      "Landscaping",
      "Auto Repair",
      "Motorcycle Riding",
      "Off-roading"
    ]
  }
];
